
app_homepage:
    path: /
    controller: AppBundle:Admin:index

app_user_list:
    path: /users/list
    controller: AppBundle:User:list

app_user_show:
    path: /user/{id}
    methods: [GET]
    requirements:
        id: \d+
    defaults:
        _controller: AppBundle:User:show

app_user_delete:
    path: /users/{id}/delete
    methods: [GET, POST]
    defaults:
        _controller: AppBundle:User:Delete

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /user/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /user/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /user/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /user/password