app:
    resource: '@AppBundle/Controller/'
    type: annotation

app_index:
    path: /
    controller: AppBundle:Default:index

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
